### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by ProwerMiles** [cjuub/okaeri-chibi-translation#27]
Can someone tell me how to apply the patches? I would appreciate it if someone could break it down in steps. Thanks!

**Comment by cjuub** [comment]
Use http://www.romhacking.net/utilities/598/

Patch: patch.xdelta (found in the downloaded zip)
Source: the original japanese rom
Output: where you want to save the english patched rom

then click Patch

**Comment by ProwerMiles** [comment]
![help](https://cloud.githubusercontent.com/assets/20349060/16705580/93a3c622-4553-11e6-820f-a023bf02f060.png)   This message pops up. I open the game and it's still JP. I did everything you've written, but I guess I'm kind of confused on the destination part. Not sure where exactly I'm supposed to save it at, but I when I save it to the ROM folder, it says "Okaeri Chibi-Robo JP.exe already exists and would you like to replace it". Not sure if that's a normal response? Maybe I'm missing something? I also have the latest version of xdeltaUI.

**Comment by cjuub** [comment]
"Okaeri Chibi-Robo JP.exe" ? Are you trying to patch a proper rom? It should not end in .exe... Also, output file must be different from source file.

Also, it could be that xdelta ui requires some .NET framework that you need to install (I'm not sure, I never use the GUI). Try googling in this case, because I don't know what it requires.

**Comment by ProwerMiles** [comment]
Alright. I'll try downloading a different ROM, and can I choose any source file? Say, I make a folder just for Okaeri Chibi-Robo, would that count as a source file?

**Comment by ProwerMiles** [comment]
I just don't know...downloaded a new ROM and the same thing's happening. Doing exactly what you're saying, but nothing's working. But, I haven't tried looking for a .NET framework yet. I'll do some more research.

**Comment by ProwerMiles** [comment]
I give up!!! Thanks anyways!

**Comment by Victor-De-leon21** [comment]
i have the same problem, ProwerMiles you did to make it work?

**Comment by Victor-De-leon21** [comment]
i need help

**Comment by cjuub** [comment]
Try some other patching GUI (maybe https://sourceforge.net/projects/xdelta3-gui/ ?), if you can't get the GUIs to work, then use xdelta in command line, it will definitively work.

Anyway, since this is not a problem with the patch, but with use of patching tools, it doesn't belong as a issue here. Ask on gbatemp (or somewhere else) where more people might answer, I don't even have Windows so I can't test the GUIs myself.
